# Generated by Django 5.2.8 on 2025-11-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_transaction_date_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='date_returned',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='status',
        ),
    ]
