# Generated by Django 5.2.8 on 2025-11-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_remove_borrowedbook_barcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
