# Generated by Django 5.2.8 on 2025-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_alter_transaction_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_reserve']},
        ),
        migrations.AlterField(
            model_name='bookbarcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
