# Generated by Django 5.2.8 on 2025-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_alter_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Author / 100$a'),
        ),
        migrations.AlterField(
            model_name='book',
            name='control_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Control Number / 001'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title / 245$a'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
