# Generated by Django 5.2.8 on 2025-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnstileAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('gate_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit')], max_length=3)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('UNAUTHORIZED', 'Unauthorized')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='turnstile_snapshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turnstile Attendance Log',
                'verbose_name_plural': 'Turnstile Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
