# Generated by Django 5.2.8 on 2025-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
